version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - nolintlint
    - revive
    - staticcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
    govet:
      # These govet checks are disabled by default, but they're useful.
      enable:
        - nilness
        - reflectvaluecompare
        - sortslice
        - unusedwrite

issues:
  # Print all issues reported by all linters.
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofumpt
